// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestApp.DbContexts;

namespace TestApp.Migrations
{
    [DbContext(typeof(ProductLibraryContext))]
    [Migration("20221031143749_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestApp.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d29888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Name = "Food"
                        },
                        new
                        {
                            Id = new Guid("da2fd509-d754-4feb-8acd-c4f9ff13ba96"),
                            Name = "Toys"
                        },
                        new
                        {
                            Id = new Guid("2902b664-1190-4c70-9915-b9c2d7680450"),
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("112b566b-ba1f-404c-b2df-e2cde39ade09"),
                            Name = "Animals"
                        },
                        new
                        {
                            Id = new Guid("5b3632c0-7b12-4e80-9c8b-3398cba7ee05"),
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = new Guid("2aadd2df-7caf-45ab-9355-7f6732985a87"),
                            Name = "Drinks"
                        });
                });

            modelBuilder.Entity("TestApp.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImgURL")
                        .HasColumnType("nvarchar(1500)")
                        .HasMaxLength(1500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Quantity")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("340c2c6b-0d1c-4b82-9d83-3cf635a3e62b"),
                            CategoryId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            ImgURL = "www.google.com",
                            Name = "Chocolate",
                            Price = "20",
                            Quantity = "1"
                        },
                        new
                        {
                            Id = new Guid("d94a64c2-2e8f-4162-9976-0ffe02d30767"),
                            CategoryId = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            ImgURL = "www.google.com",
                            Name = "Doll",
                            Price = "10",
                            Quantity = "3"
                        },
                        new
                        {
                            Id = new Guid("5b1c2b4d-45c7-402a-80c3-cc796ad49c6b"),
                            CategoryId = new Guid("2902b665-1190-4c70-9915-b9c2d7680450"),
                            ImgURL = "www.google.com",
                            Name = "Laptop",
                            Price = "100000",
                            Quantity = "10"
                        },
                        new
                        {
                            Id = new Guid("129f9ccb-149d-4d3c-ad4f-40100f38e918"),
                            CategoryId = new Guid("112b566b-ba1f-404c-b2df-e2cde39ade09"),
                            ImgURL = "www.google.com",
                            Name = "Cat",
                            Price = "100",
                            Quantity = "2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
